DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS documents;

CREATE TABLE documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(512) NOT NULL,
    file_path   VARCHAR(1024),
    chunk_count INT NOT NULL DEFAULT 0,
    status      VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    error_msg   VARCHAR(1024),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    seq         INT NOT NULL,
    content     TEXT NOT NULL,
    CONSTRAINT fk_chunks_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT uq_chunks_document_seq UNIQUE (document_id, seq)
);

CREATE INDEX idx_chunks_document_id ON chunks(document_id);
CREATE INDEX idx_documents_created_at ON documents(created_at DESC);

-- ================= M9 记忆表（H2 兼容版：IDENTITY 替代 BIGSERIAL，TEXT 替代 JSONB） =================
DROP TABLE IF EXISTS conversation_messages;
DROP TABLE IF EXISTS conversation_summaries;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS long_term_memories;

CREATE TABLE conversation_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL DEFAULT 0,
    session_id  VARCHAR(64) NOT NULL,
    role        VARCHAR(16) NOT NULL,
    content     CLOB NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_conv_msgs ON conversation_messages(user_id, session_id, id);

CREATE TABLE conversation_summaries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL DEFAULT 0,
    session_id      VARCHAR(64) NOT NULL,
    content         CLOB NOT NULL,
    last_message_id BIGINT NOT NULL,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_conv_summary UNIQUE (user_id, session_id)
);

CREATE TABLE user_profiles (
    user_id    BIGINT PRIMARY KEY,
    profile    CLOB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE long_term_memories (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL DEFAULT 0,
    content           CLOB NOT NULL,
    source_session_id VARCHAR(64),
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ltm ON long_term_memories(user_id, created_at DESC);
