DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS run_trace;

CREATE TABLE documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(512) NOT NULL,
    file_path   VARCHAR(1024),
    chunk_count INT NOT NULL DEFAULT 0,
    status      VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    error_msg   VARCHAR(1024),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    seq         INT NOT NULL,
    content     TEXT NOT NULL,
    CONSTRAINT fk_chunks_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT uq_chunks_document_seq UNIQUE (document_id, seq)
);

CREATE INDEX idx_chunks_document_id ON chunks(document_id);
CREATE INDEX idx_documents_created_at ON documents(created_at DESC);

-- S3.3 评测轨迹（与 PG init.sql 同构；evidence 数组用 H2 兼容写法，RunTraceRepository 侧 JSON 序列化存 TEXT）
CREATE TABLE run_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    question_id VARCHAR(64) NOT NULL,
    turn INT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    tool_name VARCHAR(64),
    tool_args_summary VARCHAR(500),
    result_summary VARCHAR(500),
    evidence_ids VARCHAR(500),
    evidence_types VARCHAR(500),
    routed_intent VARCHAR(32),
    critic_verdict VARCHAR(16),
    tokens_used INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_run_trace_run ON run_trace(run_id, question_id);
