DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS run_trace;

CREATE TABLE documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(512) NOT NULL,
    file_path   VARCHAR(1024),
    chunk_count INT NOT NULL DEFAULT 0,
    status      VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    error_msg   VARCHAR(1024),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    seq         INT NOT NULL,
    content     TEXT NOT NULL,
    CONSTRAINT fk_chunks_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT uq_chunks_document_seq UNIQUE (document_id, seq)
);

CREATE INDEX idx_chunks_document_id ON chunks(document_id);
CREATE INDEX idx_documents_created_at ON documents(created_at DESC);

-- S3.3 评测轨迹（与 PG init.sql 同构：无长度列全部 TEXT，避免 DECLARE_UNCERTAIN(17) 等枚举值撞 VARCHAR 限长；
-- TEXT ARRAY 两边兼容 createArrayOf("text") 绑定）
CREATE TABLE run_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL,
    question_id TEXT NOT NULL,
    turn INT NOT NULL,
    event_type TEXT NOT NULL,
    tool_name TEXT,
    tool_args_summary TEXT,
    result_summary TEXT,
    evidence_ids TEXT ARRAY,
    evidence_types TEXT ARRAY,
    routed_intent TEXT,
    critic_verdict TEXT,
    tokens_used INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_run_trace_run ON run_trace(run_id, question_id);
