package com.agenticrag.dataanalysis;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/**
 * Eval trace storage uses a file-backed H2 database so run and judge processes
 * can observe the same trace rows while the eval main datasource stays in memory.
 */
@Configuration
@Profile("eval")
public class TraceDataSourceConfig {

    @Bean("traceJdbcTemplate")
    public JdbcTemplate traceJdbcTemplate() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:file:./target/eval-trace;AUTO_SERVER=TRUE");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        initSchema(jdbcTemplate);
        return jdbcTemplate;
    }

    private void initSchema(JdbcTemplate jdbcTemplate) {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS run_trace (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id TEXT NOT NULL,
                    question_id TEXT NOT NULL,
                    turn INT NOT NULL,
                    event_type TEXT NOT NULL,
                    tool_name TEXT,
                    tool_args_summary TEXT,
                    result_summary TEXT,
                    evidence_ids TEXT ARRAY,
                    evidence_types TEXT ARRAY,
                    routed_intent TEXT,
                    critic_verdict TEXT,
                    tokens_used INT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS idx_run_trace_run ON run_trace(run_id, question_id)");
    }
}
